name: Go Release

on:
  push:
    tags:
      - "v*" # Ex: v1.0.0, v1.0, etc.

env:
  CT_REGISTRY: "docker"
  BINARY_FILENAME: "ce-arc-server"
  PACKAGES_DIR: "./server"
  GO_VERSION: "1.25.4"

jobs:
  release-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step is used to set an image tag variable
      - name: Set image tag version
        id: set-tag
        run: |
          tag="${{ github.ref_name }}"
          echo "image_tag=${tag:1}" >> "$GITHUB_OUTPUT"

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "${{ secrets.CT_REGISTRY_USERNAME }}/${{ env.BINARY_FILENAME }}"
          tags: "${{ steps.set-tag.outputs.image_tag }}"
          context: ./runner
          containerfiles: |
            ./runner/Dockerfile

      - name: "Push to the container registry"
        id: "push-to-registry"
        uses: redhat-actions/push-to-registry@v2
        with:
          image: "${{ steps.build-image.outputs.image }}"
          tags: "latest ${{ steps.build-image.outputs.tags }}"
          registry: ${{ secrets.CT_REGISTRY }}
          username: ${{ secrets.CT_REGISTRY_USERNAME }}
          password: ${{ secrets.CT_REGISTRY_PASSWORD }}

  release-bin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Download dependencies
        run: go mod download

      - name: Cross-compile binaries
        run: |
          BINARY_NAME=${{ env.BINARY_FILENAME }}
          VERSION=${{ github.ref_name }}
          PACKAGES_DIR=${{ env.PACKAGES_DIR }}
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/${BINARY_NAME}-${VERSION}-linux-amd64 "${PACKAGES_DIR}"
          GOOS=linux   GOARCH=arm64 go build -o dist/${BINARY_NAME}-${VERSION}-linux-arm64 "${PACKAGES_DIR}"
          GOOS=windows GOARCH=amd64 go build -o dist/${BINARY_NAME}-${VERSION}-windows-amd64.exe "${PACKAGES_DIR}"
          GOOS=darwin  GOARCH=arm64 go build -o dist/${BINARY_NAME}-${VERSION}-darwin-arm64 "${PACKAGES_DIR}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
